defaults: &defaults
  socket_host: http://worldclasssocket.herokuapp.com/faye

development:
  <<: *defaults
  socket_host: http://localhost:9292/faye

test:
  <<: *defaults

production:
  <<: *defaults